ALFMovers/ALFMovers/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ALFMovers.Models;

namespace ALFMovers.Controllers
{
    public class CustomerController : Controller
    {
        private ALFMoversEntities db = new ALFMoversEntities();

        // GET: Customer
        public ActionResult List()
        {

            return View(db.Customers.ToList());
        }

        public ActionResult Index()
        {
            return View();
        }

        // GET: Customer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustID,CustName,CustContact,FromAddrss,ToAddrss,IssuedDate,Status,SchedDate")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.IssuedDate = DateTime.Now;
                customer.CustID = 1;
                customer.Status = "";
                
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        public object GetClient()
        {
            
            var custid = Convert.ToInt32(Session["customerID"]);
            var customers = db.Customers.Where(c => c.CustID == custid ).FirstOrDefault();
            
            return  Json(new
            {
                name = customers.CustName,
                faddress = customers.FromAddrss,
                taddress = customers.ToAddrss,
            },JsonRequestBehavior.AllowGet);
        }

        public ActionResult Confirmation()
        {

            return View(db.Customers.ToList());
        }

        public string Accept(int id)
        {
            Customer cust = db.Customers.Find(id);
            cust.Status = "Accepted";
            db.Entry(cust).State = EntityState.Modified;
            db.SaveChanges();
            return "";
        }

        public string Reject(int id)
        {
            Customer cust = db.Customers.Find(id);
            cust.Status = "Rejected";
            db.Entry(cust).State = EntityState.Modified;
            db.SaveChanges();
            return "";
        }

        public ActionResult ForSched(int? id)
        {
            Session["customerID"] = id;
            Customer c = db.Customers.Find(id);
            var customerList = db.Customers.SqlQuery("select * from Customers WHERE Status = 'Accepted'").ToList<Customer>();

            return View(customerList);

        }
    }
}

ALFMovers/ALFMovers/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ALFMovers.Models;
using System.Data.SqlClient;

namespace ALFMovers.Controllers
{
    public class EmployeeController : Controller
    {
        private ALFMoversEntities db = new ALFMoversEntities();

        // GET: Employee
        public ActionResult Index()
        {
            return View(db.Employees.ToList());
        }

        // GET: Employee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmpID,EmpFName,EmpLName,EmpContact,Position,EmpJoined,EmpLicenset,Status")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.EmpJoined = DateTime.Now;
                employee.EmpID = 1;
                employee.Status = "Available";
                
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employee/Edit/5
        public ActionResult EditEmployee(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmpID,EmpFName,EmpLName,EmpContact,EmpJoined,EmpLicense")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Sched(int? id)
        {
            Session["customerID"] = id;
            Customer c = db.Customers.Find(id);
            var test = c.SchedDate.ToString();
            var customerList = db.Employees.SqlQuery("select * from Employee WHERE EmpID NOT IN (SELECT TransEmp.EmpID FROM TransEmp INNER JOIN Transactions ON TransEmp.TransID = Transactions.TransID where Transactions.SchedDate = '"+test+"')").ToList<Employee>();

            return View(customerList);
            
        }

        public JsonResult GetTransEmps()
        {
            var id = Session["TransactionId"];
            var empList = db.Employees.SqlQuery("select * from Employee WHERE EmpID  IN (SELECT TransEmp.EmpID FROM TransEmp INNER JOIN Transactions ON TransEmp.TransID = Transactions.TransID where Transactions.TransID = " + id + ")").ToList<Employee>();
            string all = "";
            foreach (var t in empList)
            {
                all += "<tr> <td>" + t.EmpFName.ToString() + " "+t.EmpLName.ToString()+ "</td><td>" + t.Position.ToString() + "</td><td>" + t.EmpContact.ToString() + "</td></ tr > ";
            }
            return Json(all, JsonRequestBehavior.AllowGet);

        }

        public String SchedSubmit(int id)
        {
            TransEmp E = new TransEmp();
            E.EmpID = id;
            E.TransID = Convert.ToInt32(Session["transid"]);
            db.TransEmps.Add(E);
            db.SaveChanges();
            return "Success"+id;
        }
    }
}

ALFMovers/ALFMovers/Controllers/PublicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ALFMovers.Controllers
{
    public class PublicController : Controller
    {
        // GET: Public
        public ActionResult Index()
        {
            return View();
        }

        protected override void HandleUnknownAction(string Dashboard)
        {
            try
            {
                this.View("Dashboard").ExecuteResult(this.ControllerContext);
            }
            catch(Exception ex)
            {
                Response.Redirect("Dashboard");
            }
        }
    }
}

ALFMovers/ALFMovers/Controllers/TruckController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ALFMovers.Models;

namespace ALFMovers.Controllers
{
    public class TruckController : Controller
    {
        private ALFMoversEntities db = new ALFMoversEntities();

        // GET: Truck
        public ActionResult Index()
        {
            return View(db.Trucks.ToList());
        }

        // GET: Truck/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Truck truck = db.Trucks.Find(id);
            if (truck == null)
            {
                return HttpNotFound();
            }
            return View(truck);
        }

        // GET: Truck/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Truck/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TruckPlateNo,TruckModel,Capacity,TruckAdded")] Truck truck)
        {
            if (ModelState.IsValid)
            {
                truck.TruckAdded = DateTime.Now;    
                
                db.Trucks.Add(truck);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(truck);
        }

        // GET: Truck/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Truck truck = db.Trucks.Find(id);
            if (truck == null)
            {
                return HttpNotFound();
            }
            return View(truck);
        }

        // POST: Truck/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TruckPlateNo,TruckModel,Capacity,TruckAdded")] Truck truck)
        {
            if (ModelState.IsValid)
            {
                db.Entry(truck).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(truck);
        }

        // GET: Truck/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Truck truck = db.Trucks.Find(id);
            if (truck == null)
            {
                return HttpNotFound();
            }
            return View(truck);
        }

        // POST: Truck/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Truck truck = db.Trucks.Find(id);
            db.Trucks.Remove(truck);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Sched(int? id)
        {
            Session["customerID"] = id;
            Customer c = db.Customers.Find(id);
            var test = c.SchedDate;
            var truckList = db.Trucks.SqlQuery("select * from Truck WHERE EmpID NOT IN (SELECT TransTruck.TruckPlateNo FROM TransTruck INNER JOIN Transactions ON TransTruck.TransID = Transactions.TransID where Transactions.SchedDate = '" + test + "')").ToList<Truck>();

            return View(truckList);

        }

        public String SchedSubmit(string id)
        {
            TransTruck T = new TransTruck();
            T.TruckPlateNo = id.ToString();
            T.TransID = Convert.ToInt32(Session["transid"]);
            db.TransTrucks.Add(T);
            db.SaveChanges();
            return "Success" + id;
        }

        public JsonResult GetTrucks()
        {
            int id = Convert.ToInt32(Session["customerID"]);
            Customer c = db.Customers.Find(id);
            var test = c.SchedDate;
            var truckList = db.Trucks.SqlQuery("select * from Truck WHERE Truck.Status !=  'inactive' and TruckPlateNO NOT IN (SELECT TransTruck.TruckPlateNo FROM TransTruck INNER JOIN Transactions ON TransTruck.TransID = Transactions.TransID where Transactions.SchedDate = '" + test + "')").ToList<Truck>();
            string all = "";
            foreach (var t in truckList )
            {
                all += "<tr> <td>"+t.TruckPlateNo.ToString()+"</td><td>"+t.TruckModel.ToString()+"</td><td>"+t.Capacity.ToString()+ "</td><td><input type='checkbox' value='"+t.TruckPlateNo.ToString()+"' name='truck' /></td></ tr > ";
            }
            return Json(all,JsonRequestBehavior.AllowGet); 
        }

        public JsonResult GetTransTrucks()
        {
            int id = Convert.ToInt32(Session["TransactionId"]);
            var truckList = db.Trucks.SqlQuery("select * from Truck WHERE TruckPlateNO IN (SELECT TransTruck.TruckPlateNo FROM TransTruck INNER JOIN Transactions ON TransTruck.TransID = Transactions.TransID where Transactions.TransID = " + id + ")").ToList<Truck>();
            string all = "";
            foreach (var t in truckList)
            {
                all += "<tr> <td>" + t.TruckPlateNo.ToString() + "</td><td>" + t.TruckModel.ToString() + "</td><td>" + t.Capacity.ToString() + "</td></ tr > ";
            }
            return Json(all, JsonRequestBehavior.AllowGet);
        }

        public string ChangeStatus(string id)
        {
            Truck truck = db.Trucks.Find(id);
            if (truck.Status=="active")
            {
                truck.Status = "Inactive";
                db.Entry(truck).State = EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                truck.Status = "Active";
                db.Entry(truck).State = EntityState.Modified;
                db.SaveChanges();
            }
            return "Status Changed to " + truck.Status;
        }
    }
}

ALFMovers/ALFMovers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ALF-TM System</title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap/dist/css/bootstrap.min.css " runat="server">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/bower_components/font-awesome/css/font-awesome.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Content/bower_components/Ionicons/css/ionicons.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/AdminLTE.min.css">

    <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Content/dist/css/skins/_all-skins.min.css">

    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">

    <link rel="stylesheet" href="~/Content/mycss.css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!-- ADD THE CLASS fixed TO GET A FIXED HEADER AND SIDEBAR LAYOUT -->
<!-- the fixed layout is not compatible with sidebar-mini -->
<body class="hold-transition skin-black-light fixed sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>A</b>LF</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><img src="~/Content/img/1.png" width="200" height="40"></span>
            </a>


            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">

                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </nav>
        </header>

        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">

            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">

                <!-- sidebar menu: : NAVIGATION -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MAIN NAVIGATION</li>

                    <!-- sidebar menu: : DASHBOARD -->
                    <li><a href="@Url.Action("Dashboard","Public")"><i class="glyphicon glyphicon-home"></i> <span>Dashboard</span></a></li>

                    <!-- sidebar menu: : Accept and reject -->
                    <li><a href="@Url.Action("Confirmation","Customer")"><i class="glyphiocn glyphicon glyphicon-ok"></i> <span>Service Requests</span></a></li>

                    <!-- sidebar menu: : TRANSACTIONS -->
                    <li class="treeview">
                        <a href="#">
                            <i class="glyphicon glyphicon-tasks"></i>
                            <span>Transactions</span>
                            <span class="pull-right-container">
                                <span class="label label-primary pull-right"></span>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("ForSched","Customer")"><i class="fa fa-calendar"></i>For Schedule</a></li>
                            <li><a href=""><i class="fa fa-wrench"></i>Pending</a></li>
                            <li><a href=""><i class="fa fa-check-circle"></i>Finished</a></li>
                        </ul>
                    </li>

                    <!-- sidebar menu: : EMPLOYEE -->
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-users"></i>
                            <span>Employee</span>
                            <span class="pull-right-container">
                                <span class="label label-primary pull-right"></span>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index","Employee")"><i class="fa fa-user"></i> List of Employees</a></li>
                            <li><a href="@Url.Action("Create","Employee")"><i class="fa fa-user-plus"></i> Add Employee</a></li>
                        </ul>
                    </li>

                    <!-- sidebar menu: : TRUCK -->
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-truck"></i>
                            <span>Truck</span>
                            <span class="pull-right-container">
                                <span class="label label-primary pull-right"></span>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index","Truck")"><i class="fa fa-truck"></i> List of Trucks</a></li>
                            <li><a href="@Url.Action("Create","Truck")"><i class="fa fa-plus-square"></i>Add Truck</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- =============================================== -->
        <!-- FOOTER -->
        <div class="body">
            @RenderBody()
            <footer class="main-footer">
                <strong>Copyright &copy; 2014-2016 </strong> AFL Truck Management by SJEFN. All rights reserved.
            </footer>
        </div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="/Content/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap 3.3.7 -->
    <script src="/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- SlimScroll -->
    <script src="/Content/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>

    <!-- FastClick -->
    <script src="/Content/bower_components/fastclick/lib/fastclick.js"></script>

    <!-- AdminLTE App -->
    <script src="/Content/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="/Content/dist/js/demo.js"></script>

    <!-- bootstrap datepicker -->
    <script src="~/Content/bower_components/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
</body>
</html>